"""initial migration

Revision ID: 11667a07317c
Revises: 
Create Date: 2024-10-24 15:27:24.258608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11667a07317c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_value'), 'api_key', ['value'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=True),
    sa.Column('login', sa.String(length=125), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_id'), 'connection', ['id'], unique=False)
    op.create_index(op.f('ix_connection_login'), 'connection', ['login'], unique=True)
    op.create_index(op.f('ix_connection_name'), 'connection', ['name'], unique=False)
    op.create_index(op.f('ix_connection_password'), 'connection', ['password'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['api_key'], ['api_key.value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'api_key')
    )
    op.create_table('campaign',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('msg_template', sa.String(), nullable=True),
    sa.Column('msg_total', sa.Integer(), nullable=True),
    sa.Column('msg_sent', sa.Integer(), nullable=True),
    sa.Column('msg_delivered', sa.Integer(), nullable=True),
    sa.Column('msg_undelivered', sa.Integer(), nullable=True),
    sa.Column('msg_failed', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.DateTime(), nullable=True),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('stop_ts', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_create_ts'), 'campaign', ['create_ts'], unique=False)
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=True)
    op.create_index(op.f('ix_campaign_msg_delivered'), 'campaign', ['msg_delivered'], unique=False)
    op.create_index(op.f('ix_campaign_msg_failed'), 'campaign', ['msg_failed'], unique=False)
    op.create_index(op.f('ix_campaign_msg_sent'), 'campaign', ['msg_sent'], unique=False)
    op.create_index(op.f('ix_campaign_msg_template'), 'campaign', ['msg_template'], unique=False)
    op.create_index(op.f('ix_campaign_msg_total'), 'campaign', ['msg_total'], unique=False)
    op.create_index(op.f('ix_campaign_msg_undelivered'), 'campaign', ['msg_undelivered'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_order'), 'campaign', ['order'], unique=False)
    op.create_index('ix_campaign_schedule_gin', 'campaign', ['schedule'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_campaign_start_ts'), 'campaign', ['start_ts'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_stop_ts'), 'campaign', ['stop_ts'], unique=False)
    op.create_table('connection_api_keys',
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['api_key'], ['api_key.value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id', 'api_key')
    )
    op.create_table('campaign_api_keys',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['api_key'], ['api_key.value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'api_key')
    )
    op.create_table('campaign_dst',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('dst_addr', sa.String(), nullable=True),
    sa.Column('field_1', sa.String(), nullable=True),
    sa.Column('field_2', sa.String(), nullable=True),
    sa.Column('field_3', sa.String(), nullable=True),
    sa.Column('field_4', sa.String(), nullable=True),
    sa.Column('field_5', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('create_ts', sa.DateTime(), nullable=True),
    sa.Column('sent_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_dst_create_ts'), 'campaign_dst', ['create_ts'], unique=False)
    op.create_index(op.f('ix_campaign_dst_dst_addr'), 'campaign_dst', ['dst_addr'], unique=False)
    op.create_index(op.f('ix_campaign_dst_field_1'), 'campaign_dst', ['field_1'], unique=False)
    op.create_index(op.f('ix_campaign_dst_field_2'), 'campaign_dst', ['field_2'], unique=False)
    op.create_index(op.f('ix_campaign_dst_field_3'), 'campaign_dst', ['field_3'], unique=False)
    op.create_index(op.f('ix_campaign_dst_field_4'), 'campaign_dst', ['field_4'], unique=False)
    op.create_index(op.f('ix_campaign_dst_field_5'), 'campaign_dst', ['field_5'], unique=False)
    op.create_index(op.f('ix_campaign_dst_id'), 'campaign_dst', ['id'], unique=True)
    op.create_index(op.f('ix_campaign_dst_sent_ts'), 'campaign_dst', ['sent_ts'], unique=False)
    op.create_index(op.f('ix_campaign_dst_status'), 'campaign_dst', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_dst_text'), 'campaign_dst', ['text'], unique=False)
    op.create_index(op.f('ix_campaign_dst_update_ts'), 'campaign_dst', ['update_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_dst_update_ts'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_text'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_status'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_sent_ts'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_id'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_field_5'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_field_4'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_field_3'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_field_2'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_field_1'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_dst_addr'), table_name='campaign_dst')
    op.drop_index(op.f('ix_campaign_dst_create_ts'), table_name='campaign_dst')
    op.drop_table('campaign_dst')
    op.drop_table('campaign_api_keys')
    op.drop_table('connection_api_keys')
    op.drop_index(op.f('ix_campaign_stop_ts'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_start_ts'), table_name='campaign')
    op.drop_index('ix_campaign_schedule_gin', table_name='campaign', postgresql_using='gin')
    op.drop_index(op.f('ix_campaign_order'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_undelivered'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_total'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_template'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_sent'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_failed'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_msg_delivered'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_create_ts'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_connection_password'), table_name='connection')
    op.drop_index(op.f('ix_connection_name'), table_name='connection')
    op.drop_index(op.f('ix_connection_login'), table_name='connection')
    op.drop_index(op.f('ix_connection_id'), table_name='connection')
    op.drop_table('connection')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_api_key_value'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
